import "../styles/globals.css"
import Head from "next/head"
import Navbar from "../components/Navbar"
import { MoralisProvider } from "react-moralis"

function MyApp({ Component, pageProps }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MoralisProvider initializeOnMount={false}>
                <Navbar />
                <Component {...pageProps} />
            </MoralisProvider>
        </>
    )
}

export default MyApp
